Repository jwu-wa-yellow/todo-list, pull requests merged in 2022-04, with the labels that each got.

#7 Update issue templates
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: 문서

#11 [프로젝트 구조] To do List 레이아웃 구성
  .gitignore
  client/dist/app.bundle.js
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/public/js/app.js
  client/public/js/main.js
  client/public/js/mainService.js
  client/public/style/main.scss
  client/webpack.config.js
Labels: 기능

#19 정적페이지 card,alert,layer
  client/public/asset/icon/icon-card-add-button-blue.svg
  client/public/asset/icon/icon-card-delete-button-red.svg
  client/public/asset/icon/icon-column-add-button-blue.svg
  client/public/asset/icon/icon-delete-button-bold.svg
  client/public/index.html
  client/public/js/views/aside/AsideView.js
  client/public/js/views/aside/_aside.scss
  client/public/js/views/card/_card.scss
  client/public/js/views/column/_column.scss
  client/public/js/views/header/_header.scss
  client/public/js/views/main/_main.scss
  client/public/stylesheet/_global.scss
  client/public/stylesheet/_variable.scss
  client/public/stylesheet/style.scss
  client/public/stylesheet/util/_font.scss
  client/public/stylesheet/util/_mixin.scss
  client/public/stylesheet/util/_reset.scss
  client/public/stylesheet/util/_variable.scss
Labels: 기능

#24 [js] aside, header 기본 구조 만들기
  client/public/index.html
  client/public/js/app.js
  client/public/js/tempStorage.js
  client/public/js/views/aside/_aside.scss
  client/public/js/views/aside/aside.js
  client/public/js/views/column/column.js
  client/public/js/views/header/header.js
  client/public/js/views/history/_history.scss
  client/public/js/views/history/history.js
  client/public/js/views/renderer.js
  client/public/stylesheet/style.scss
Labels: Feat
